# Postgres config
SOURCE_CONNECTOR_NAME="postgres-source-connector"
POSTGRES_HOST="192.168.25.134"
POSTGRES_PORT=5432
POSTGRES_USER="odoo"
POSTGRES_PASSWORD="root"
DATABASE_DBNAME="odoo"
TOPIC_PREFIX="postgres"
TABLE_INCLUDE_LIST=""
